//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REGISTROCEL_IPEAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CIUDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_CIUDAD()
        {
            this.CAT_FABRICA = new HashSet<CAT_FABRICA>();
        }
    
        public short id { get; set; }
        public string pais { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        public virtual CAT_PAIS CAT_PAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_FABRICA> CAT_FABRICA { get; set; }
    }
}
