//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REGISTROCEL_IPEAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PAIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_PAIS()
        {
            this.CAT_CIUDAD = new HashSet<CAT_CIUDAD>();
        }
    
        public string id { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_CIUDAD> CAT_CIUDAD { get; set; }
    }
}
