//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REGISTROCEL_IPEAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_DISPOSITIVO
    {
        public int id { get; set; }
        public string no_serie { get; set; }
        public int gama { get; set; }
        public short color { get; set; }
        public short fabrica_ensamblaje { get; set; }
        public decimal costo_fabricacion_final { get; set; }
        public System.DateTime fecha_in { get; set; }
        public string usuario_in { get; set; }
        public Nullable<System.DateTime> fech_mod { get; set; }
        public string usuario_mod { get; set; }
    
        public virtual CAT_COLOR CAT_COLOR { get; set; }
        public virtual CAT_FABRICA CAT_FABRICA { get; set; }
        public virtual CAT_GAMA CAT_GAMA { get; set; }
    }
}
